# coding: utf-8

"""
    alertmanager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

import labs_alert_manager_client
from labs_alert_manager_client.api.welcome_api import WelcomeApi  # noqa: E501
from labs_alert_manager_client.rest import ApiException


class TestWelcomeApi(unittest.TestCase):
    """WelcomeApi unit test stubs"""

    def setUp(self):
        self.api = labs_alert_manager_client.api.welcome_api.WelcomeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_welcome(self):
        """Test case for get_welcome

        """
        pass


if __name__ == '__main__':
    unittest.main()
