# coding: utf-8

"""
    alertmanager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import openapi_client
from openapi_client.api.default_api import DefaultApi  # noqa: E501
from openapi_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_client_app_get_delete(self):
        """Test case for delete_client_app_get_delete

        """
        pass

    def test_get_client_app_get(self):
        """Test case for get_client_app_get

        """
        pass

    def test_get_client_app_get_all(self):
        """Test case for get_client_app_get_all

        """
        pass

    def test_get_docs(self):
        """Test case for get_docs

        """
        pass

    def test_get_health_check(self):
        """Test case for get_health_check

        """
        pass

    def test_get_swagger_json(self):
        """Test case for get_swagger_json

        """
        pass

    def test_post_client_app_post(self):
        """Test case for post_client_app_post

        """
        pass

    def test_put_client_app_put(self):
        """Test case for put_client_app_put

        """
        pass


if __name__ == '__main__':
    unittest.main()
