# coding: utf-8

"""
    alertmanager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from labs_alert_manager_client.models.pagination_schema import PaginationSchema  # noqa: E501

class TestPaginationSchema(unittest.TestCase):
    """PaginationSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginationSchema:
        """Test PaginationSchema
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginationSchema`
        """
        model = PaginationSchema()  # noqa: E501
        if include_optional:
            return PaginationSchema(
                page = 56,
                page_size = 56,
                rows = [
                    None
                    ],
                total_rows = 56
            )
        else:
            return PaginationSchema(
                page = 56,
                page_size = 56,
                rows = [
                    None
                    ],
                total_rows = 56,
        )
        """

    def testPaginationSchema(self):
        """Test PaginationSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
