# coding: utf-8

"""
    alertmanager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from labs_alert_manager_client.api.channels_api import ChannelsApi


class TestChannelsApi(unittest.TestCase):
    """ChannelsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ChannelsApi()

    def tearDown(self) -> None:
        pass

    def test_delete_policy_channels_delete(self) -> None:
        """Test case for delete_policy_channels_delete

        """
        pass

    def test_get_policy_channels_get(self) -> None:
        """Test case for get_policy_channels_get

        """
        pass

    def test_get_policy_channels_get_all(self) -> None:
        """Test case for get_policy_channels_get_all

        """
        pass

    def test_post_policy_channels_post(self) -> None:
        """Test case for post_policy_channels_post

        """
        pass

    def test_post_policy_channels_test(self) -> None:
        """Test case for post_policy_channels_test

        """
        pass

    def test_put_policy_channels_put(self) -> None:
        """Test case for put_policy_channels_put

        """
        pass


if __name__ == '__main__':
    unittest.main()
