# coding: utf-8

"""
    alertmanager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from labs_alert_manager_client.api.notifications_api import NotificationsApi


class TestNotificationsApi(unittest.TestCase):
    """NotificationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NotificationsApi()

    def tearDown(self) -> None:
        pass

    def test_get_notification_log_get(self) -> None:
        """Test case for get_notification_log_get

        """
        pass

    def test_get_notification_log_get_all(self) -> None:
        """Test case for get_notification_log_get_all

        """
        pass

    def test_post_notification_log_resend(self) -> None:
        """Test case for post_notification_log_resend

        """
        pass


if __name__ == '__main__':
    unittest.main()
