# coding: utf-8

"""
    alertmanager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

import labs_alert_manager_client
from labs_alert_manager_client.api.events_api import EventsApi  # noqa: E501
from labs_alert_manager_client.rest import ApiException


class TestEventsApi(unittest.TestCase):
    """EventsApi unit test stubs"""

    def setUp(self):
        self.api = labs_alert_manager_client.api.events_api.EventsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_events_get(self):
        """Test case for get_events_get

        """
        pass

    def test_get_events_get_all(self):
        """Test case for get_events_get_all

        """
        pass

    def test_get_events_parameters_get(self):
        """Test case for get_events_parameters_get

        """
        pass

    def test_post_events_post(self):
        """Test case for post_events_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
