# coding: utf-8

"""
    alertmanager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from labs_alert_manager_client.api.docs_api import DocsApi


class TestDocsApi(unittest.TestCase):
    """DocsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DocsApi()

    def tearDown(self) -> None:
        pass

    def test_get_swagger_json(self) -> None:
        """Test case for get_swagger_json

        """
        pass

    def test_get_swagger_yml(self) -> None:
        """Test case for get_swagger_yml

        """
        pass


if __name__ == '__main__':
    unittest.main()
