# coding: utf-8

"""
    alertmanager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

import labs_alert_manager_client
from labs_alert_manager_client.api.policies_api import PoliciesApi  # noqa: E501
from labs_alert_manager_client.rest import ApiException


class TestPoliciesApi(unittest.TestCase):
    """PoliciesApi unit test stubs"""

    def setUp(self):
        self.api = labs_alert_manager_client.api.policies_api.PoliciesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_policies_delete(self):
        """Test case for delete_policies_delete

        """
        pass

    def test_get_policies_get(self):
        """Test case for get_policies_get

        """
        pass

    def test_get_policies_get_all(self):
        """Test case for get_policies_get_all

        """
        pass

    def test_post_policies_post(self):
        """Test case for post_policies_post

        """
        pass

    def test_put_policies_put(self):
        """Test case for put_policies_put

        """
        pass


if __name__ == '__main__':
    unittest.main()
