# coding: utf-8

"""
    alertmanager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from labs_alert_manager_client.api.events_api import EventsApi  # noqa: E501


class TestEventsApi(unittest.TestCase):
    """EventsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EventsApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_delete_events_parameters_delete(self) -> None:
        """Test case for delete_events_parameters_delete

        """
        pass

    def test_get_events_get(self) -> None:
        """Test case for get_events_get

        """
        pass

    def test_get_events_get_all(self) -> None:
        """Test case for get_events_get_all

        """
        pass

    def test_get_events_parameters_get(self) -> None:
        """Test case for get_events_parameters_get

        """
        pass

    def test_post_events_post(self) -> None:
        """Test case for post_events_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
