# coding: utf-8

"""
    alertmanager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Dict, List
from pydantic import BaseModel, Field, StrictInt, conlist

class PaginationSchema(BaseModel):
    """
    PaginationSchema
    """
    page: StrictInt = Field(...)
    page_size: StrictInt = Field(..., alias="pageSize")
    rows: conlist(Dict[str, Any]) = Field(...)
    total_rows: StrictInt = Field(..., alias="totalRows")
    __properties = ["page", "pageSize", "rows", "totalRows"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PaginationSchema:
        """Create an instance of PaginationSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PaginationSchema:
        """Create an instance of PaginationSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PaginationSchema.parse_obj(obj)

        _obj = PaginationSchema.parse_obj({
            "page": obj.get("page"),
            "page_size": obj.get("pageSize"),
            "rows": obj.get("rows"),
            "total_rows": obj.get("totalRows")
        })
        return _obj


